// Railway-compatible server for Next.js standalone output
// Simply sets HOSTNAME=0.0.0.0 and delegates to Next.js standalone server
//
// This file is copied into the standalone output directory during build.
// Next.js standalone server reads HOSTNAME and PORT from environment.

process.env.HOSTNAME = process.env.HOSTNAME || '0.0.0.0';

// In production (standalone), the real server is generated by Next.js at:
// .next/standalone/server.js
// This wrapper just ensures proper env vars are set before loading it.

const fs = require('fs');
const path = require('path');

// Check if we are in standalone output (no src dir)
const isStandalone = !fs.existsSync(path.join(__dirname, 'src'));

if (isStandalone) {
  // We're inside the standalone output directory
  // Load and run the Next.js generated standalone server
  // It will pick up HOSTNAME and PORT from process.env
  try {
    require('./server.js');
  } catch (err) {
    // If the standalone server.js doesn't exist or fails,
    // try the Next.js internal server
    console.error('Failed to load standalone server:', err.message);

    // Last resort: start Next.js manually
    const http = require('http');
    const port = parseInt(process.env.PORT || '3000', 10);
    const hostname = process.env.HOSTNAME || '0.0.0.0';

    try {
      const next = require('next');
      const app = next({ dev: false, hostname, port });
      const handle = app.getRequestHandler();

      app.prepare().then(() => {
        http.createServer((req, res) => {
          handle(req, res, new URL(req.url, `http://${hostname}:${port}`));
        }).listen(port, hostname, () => {
          console.log(`> Ready on http://${hostname}:${port}`);
        });
      });
    } catch (err2) {
      console.error('All server start methods failed:', err2.message);
      process.exit(1);
    }
  }
} else {
  // Dev mode: start next dev server
  const { execSync } = require('child_process');
  const port = process.env.PORT || '3000';
  const hostname = process.env.HOSTNAME || '0.0.0.0';

  console.log(`Starting dev server on ${hostname}:${port}...`);
  execSync(`npx next dev -p ${port} -H ${hostname}`, { stdio: 'inherit' });
}
